parameters:
    da2e.filtration.filter.filter.sphinx.api.text_filter_class: Da2e\FiltrationBundle\Filter\Filter\Sphinx\API\TextFilter
    da2e.filtration.filter.filter.sphinx.api.number_filter_class: Da2e\FiltrationBundle\Filter\Filter\Sphinx\API\NumberFilter
    da2e.filtration.filter.filter.sphinx.api.date_filter_class: Da2e\FiltrationBundle\Filter\Filter\Sphinx\API\DateFilter
    da2e.filtration.filter.filter.sphinx.api.choice_filter_class: Da2e\FiltrationBundle\Filter\Filter\Sphinx\API\ChoiceFilter
    da2e.filtration.filter.filter.sphinx.api.entity_filter_class: Da2e\FiltrationBundle\Filter\Filter\Sphinx\API\EntityFilter

services:
    da2e.filtration.filter.filter.sphinx.api.text_filter:
        class: %da2e.filtration.filter.filter.sphinx.api.text_filter_class%
        tags:
            - { name:  da2e.filtration.manager.filter, alias: da2e_sphinx_text_filter }

    da2e.filtration.filter.filter.sphinx.api.number_filter:
        class: %da2e.filtration.filter.filter.sphinx.api.number_filter_class%
        tags:
            - { name:  da2e.filtration.manager.filter, alias: da2e_sphinx_number_filter }

    da2e.filtration.filter.filter.sphinx.api.date_filter:
        class: %da2e.filtration.filter.filter.sphinx.api.date_filter_class%
        tags:
            - { name:  da2e.filtration.manager.filter, alias: da2e_sphinx_date_filter }

    da2e.filtration.filter.filter.sphinx.api.choice_filter:
        class: %da2e.filtration.filter.filter.sphinx.api.choice_filter_class%
        tags:
            - { name:  da2e.filtration.manager.filter, alias: da2e_sphinx_choice_filter }

    da2e.filtration.filter.filter.sphinx.api.entity_filter:
        class: %da2e.filtration.filter.filter.sphinx.api.entity_filter_class%
        tags:
            - { name:  da2e.filtration.manager.filter, alias: da2e_sphinx_entity_filter }
