parameters:
    da2e.filtration.filter.chain.filter_chain_class: Da2e\FiltrationBundle\Filter\Chain\FilterChain
    da2e.filtration.filter.collection.collection_class: Da2e\FiltrationBundle\Filter\Collection\Collection
    da2e.filtration.filter.collection.creator.collection_creator_class: Da2e\FiltrationBundle\Filter\Collection\Creator\CollectionCreator
    da2e.filtration.filter.creator.filter_creator_class: Da2e\FiltrationBundle\Filter\Creator\FilterCreator
    da2e.filtration.filter.filter_option.filter_option_handler_class: Da2e\FiltrationBundle\Filter\FilterOption\FilterOptionHandler
    da2e.filtration.filter.executor.filter_executor_class: Da2e\FiltrationBundle\Filter\Executor\FilterExecutor
    da2e.filtration.manager.filter_super_manager_class: Da2e\FiltrationBundle\Manager\FilterSuperManager
    da2e.filtration.form.creator.form_creator_class: Da2e\FiltrationBundle\Form\Creator\FormCreator
    da2e.filtration.form.type.filter_type_class: Da2e\FiltrationBundle\Form\Type\FilterType

    da2e.filtration.form.creator.form_creator_config:
        form_filter_type_class: %da2e.filtration.form.type.filter_type_class%

services:
    da2e.filtration.filter.chain.filter_chain:
        class: %da2e.filtration.filter.chain.filter_chain_class%

    da2e.filtration.filter.creator.filter_creator:
        class: %da2e.filtration.filter.creator.filter_creator_class%
        arguments: [ @da2e.filtration.filter.chain.filter_chain ]

    da2e.filtration.filter.filter_option.filter_option_handler:
        class: %da2e.filtration.filter.filter_option.filter_option_handler_class%

    da2e.filtration.filter.collection.creator.collection_creator:
        class: %da2e.filtration.filter.collection.creator.collection_creator_class%
        arguments: [ %da2e.filtration.filter.collection.collection_class% ]

    da2e.filtration.filter.executor.filter_executor:
        class: %da2e.filtration.filter.executor.filter_executor_class%
        arguments: [ %da2e.filtration.config.handler_types% ]

    da2e.filtration.manager.filter_super_manager:
        class: %da2e.filtration.manager.filter_super_manager_class%
        arguments:
            - @da2e.filtration.filter.collection.creator.collection_creator
            - @da2e.filtration.form.creator.form_creator
            - @da2e.filtration.filter.executor.filter_executor

    da2e.filtration.form.creator.form_creator:
        class: %da2e.filtration.form.creator.form_creator_class%
        arguments: [ @form.factory, %da2e.filtration.form.creator.form_creator_config% ]
